loki:
  structuredConfig:
    ingester:
      max_transfer_retries: 0
      chunk_idle_period: 1h
      chunk_target_size: 1536000
      max_chunk_age: 1h
    storage_config:
      aws:
        endpoint: 34.28.74.21:9000
        insecure: true
        bucketnames: loki-data
        access_key_id: epWpnQsIwOpXHpne
        secret_access_key: XAxroZhe7Z9lQQcSWJi9ufbokM2I2H5q
        s3forcepathstyle: true
      boltdb_shipper:
        shared_store: s3
    schema_config:
      configs:
        - from: 2022-06-21
          store: boltdb-shipper
          object_store: s3
          schema: v12
          index:
            prefix: loki_index_
            period: 24h

distributor:
  replicas: 1

ingester:
  replicas: 1
  persistence:
    enabled: true
    size: 1Gi
    storageClass: local-path

querier:
  replicas: 1
  persistence:
    enabled: true
    size: 1Gi
    storageClass: local-path

queryFrontend:
  replicas: 1

gateway:
  nginxConfig:
    httpSnippet: |-
      client_max_body_size 100M;
    serverSnippet: |-
      client_max_body_size 100M;
